# Deployment do Grafana

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "/grafana"
            - name: GF_USERS_ALLOW_ORG_CREATE
              value: "false"
                #- name: GF_SERVER_SERVE_FROM_SUB_PATH
                #value: "true"
---

# Service do Grafana 

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana

