apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: public-access
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: public-access-binding
subjects:
  - kind: Group
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: public-access
  apiGroup: rbac.authorization.k8s.io

